include ../common/go/common.mk

db=etcd

.PHONY:ivxv_storage_db
ivxv_storage_db:
	cp $(ROOTDIR)/common/external/database/$(db)/ivxv-storage_db_install.sh bin/
	cp $(ROOTDIR)/common/external/database/$(db)/ivxv-storage_db_uninstall.sh bin/
	cp $(ROOTDIR)/common/external/database/$(db)/ivxv-storage_db.tar.gz bin/
