@startuml
autonumber
actor "EHS operaator" as ac_ehs
participant "EHS" as ehs
'participant "VIS" as vis
actor "VIS operaator" as ac_vis
'participant "RR" as rr


activate ehs
ac_vis -> ac_ehs : Nimekirjade verifitseerimisvõti
ac_vis -> ac_ehs : VIS3 teenuse otspunkt ja sertifikaat
ac_ehs -> ac_vis : EHS sertifikaat

ac_ehs -> ehs : Nimekirjade verifitseerimisvõti
ac_ehs -> ehs : VIS3 teenuse otspunkt ja sertifikaat
deactivate ehs
@enduml
