@startuml
autonumber

actor "EHS operator" as ac_ehs
participant "EHS" as ehs
actor "VIS operator" as ac_vis

activate ehs
ac_vis -> ac_ehs : Verification keys for lists
ac_vis -> ac_ehs : Endpoint and certificate for VIS3 service
ac_ehs -> ac_vis : EHS certificate

ac_ehs -> ehs : Verification keys for lists
ac_ehs -> ehs : Endpoint and certificate for VIS3 service
deactivate ehs
@enduml

