@startuml
autonumber
actor "EHS operaator" as ac_ehs
participant "EHS" as ehs
participant "VIS" as vis
'actor "VIS operaator" as ac_vis
'participant "RR" as rr

activate vis
'activate rr
activate ehs

ehs -> vis : Anna valijate nimekirja muudatused (1)
vis -> ehs : Veel mitte. HTTP 404 - no-content

...mingi aja möödudes...

ehs -> vis : Anna valijate nimekirja muudatused (1)
vis -> ehs : Muudatusnimekiri 1
ehs -> ehs : Impordi muudatusnimekiri 1

...mingi aja möödudes...

ehs -> vis : Anna valijate nimekirja muudatused (2)
vis -> ehs : Muudatusnimekiri 2
ehs -> ehs : Impordi muudatusnimekiri 2

deactivate vis
'deactivate rr
deactivate ehs
@enduml
