@startuml
autonumber
actor "EHS operaator" as ac_ehs
participant "EHS" as ehs
participant "VIS" as vis
actor "VIS3 operaator" as ac_vis
actor "VIS3 peakasutaja" as ac_vis_main
participant "RR" as rr

activate vis
activate rr

ac_vis -> vis : Algata valijate algnimekirja hankimine
vis -> rr : RRValimisteAlgNimekiriRequest
rr -> vis : RRValimisteAlgNimekiriResponse

...Algnimekiri edastatakse EHS operaatorile...

ac_vis_main -> vis: Ekspordi valijate algnimekiri
vis -> ac_vis_main: Valijate algnimekiri 0

...EHS on valmis algnimekirja rakendama...

ac_vis_main -> ac_vis_main: Allkirjasta valijate algnimekiri 0
ac_vis_main -> ac_ehs: Edasta allkirjastatud valijate algnimekiri 0
activate ehs
ac_ehs -> ehs: Impordi valijate algnimekiri 0
ehs -> ehs: Impordi valijate algnimekiri 0

...Algab elektrooniline hääletamine...
par Paralleelprotsessid
	loop Intervalliga X aja tagant
      vis -> rr : RRValimisteNimekirjaMuudatusedRequest
      rr -> vis : RRValimisteNimekirjaMuudatusedResponse
	end

	else

	ehs -> vis : Anna valijate nimekirja muudatused (1)
	vis -> ehs : Veel mitte. HTTP 404 - no-content

end

deactivate vis
deactivate rr
deactivate ehs

@enduml
