@startuml
autonumber

actor "EHS operator" as ac_ehs
participant "EHS" as ehs
participant "VIS" as vis

activate vis
activate ehs

ehs -> vis : Provide voter list changes (3)
vis -> ehs : Change list 3
ehs -> ehs : Import change list 3
ehs -> ac_ehs: Issue with loading Change list 3

...EHS-side issue resolved...

ehs -> vis : Provide voter list changes (3)
vis -> ehs : Change list 3
ehs -> ehs : Import change list 3

...after some time...

ehs -> vis : Provide voter list changes (4)
vis -> ehs : Change list 4
ehs -> ehs : Import change list 4
ehs -> ac_ehs: Issue with loading Change list 4

...RR- or VIS-side issue resolved, Change list 5 created...

ac_ehs -> ehs: Signed directive to skip Change list 4

ehs -> vis : Provide voter list changes (5)
vis -> ehs : Change list 5
ehs -> ehs : Import change list 5

...after some time...

ehs -> vis : Provide voter list changes (7)
vis -> ehs : Conflict. HTTP 409 - conflict
ehs -> ac_ehs: Sequence number error, issue with loading

...EHS-side issue resolved...

ehs -> vis : Provide voter list changes (6)
vis -> ehs : Change list 6
ehs -> ehs : Import change list 6

deactivate vis
deactivate ehs
@enduml

