@startuml
autonumber
actor "EHS operaator" as ac_ehs
participant "EHS" as ehs
participant "VIS" as vis
'actor "VIS operaator" as ac_vis
'participant "RR" as rr

activate vis
'activate rr
activate ehs

ehs -> vis : Anna valijate nimekirja muudatused (3)
vis -> ehs : Muudatusnimekiri 3
ehs -> ehs : Impordi muudatusnimekiri 3
ehs -> ac_ehs: Muudatusnimekiri 3, laadimisel probleem

...EHS-poolne tõrge lahendatakse...

ehs -> vis : Anna valijate nimekirja muudatused (3)
vis -> ehs : Muudatusnimekiri 3
ehs -> ehs : Impordi muudatusnimekiri 3

...mingi aja möödudes...

ehs -> vis : Anna valijate nimekirja muudatused (4)
vis -> ehs : Muudatusnimekiri 4
ehs -> ehs : Impordi muudatusnimekiri 4
ehs -> ac_ehs: Muudatusnimekiri 4, laadimisel probleem

...RR- või VIS-poolne tõrge lahendatakse, tekib muudatusnimekiri 5...

ac_ehs -> ehs: Allkirjastatud korraldus jätta vahele muudatusnimekiri 4

ehs -> vis : Anna valijate nimekirja muudatused (5)
vis -> ehs : Muudatusnimekiri 5
ehs -> ehs : Impordi muudatusnimekiri 5

...mingi aja möödudes...

ehs -> vis : Anna valijate nimekirja muudatused (7)
vis -> ehs : Konflikt. HTTP 409 - conflict
ehs -> ac_ehs: Järjenumbri viga, laadimisel probleem

...EHS-poolne tõrge lahendatakse...

ehs -> vis : Anna valijate nimekirja muudatused (6)
vis -> ehs : Muudatusnimekiri 6
ehs -> ehs : Impordi muudatusnimekiri 6

deactivate vis
'deactivate rr
deactivate ehs
@enduml
