@startuml
autonumber

actor "EHS operator" as ac_ehs
participant "EHS" as ehs
participant "VIS" as vis
actor "VIS3 operator" as ac_vis
actor "VIS3 main user" as ac_vis_main
participant "RR" as rr

activate vis
activate rr

ac_vis -> vis : Initiate acquiring initial voter list
vis -> rr : RRVotersInitialListRequest
rr -> vis : RRVotersInitialListResponse

...Initial list is transmitted to EHS operator...

ac_vis_main -> vis: Export initial voter list
vis -> ac_vis_main: Initial voter list 0

...EHS is ready to apply the initial voter list...

ac_vis_main -> ac_vis_main: Sign initial voter list 0
ac_vis_main -> ac_ehs: Transmit signed initial voter list 0
activate ehs
ac_ehs -> ehs: Import initial voter list 0
ehs -> ehs: Import initial voter list 0

...Electronic voting begins...
par Parallel_processes
    loop Every X time interval
        vis -> rr : RRVotingListChangesRequest
        rr -> vis : RRVotingListChangesResponse
    end

    else

    ehs -> vis : Provide voter list changes (1)
    vis -> ehs : Not yet. HTTP 404 - no-content

end

deactivate vis
deactivate rr
deactivate ehs

@enduml
