@startuml
autonumber

actor "EHS operator" as ac_ehs
participant "EHS" as ehs
participant "VIS" as vis

activate vis
activate ehs

ehs -> vis : Provide voter list changes (1)
vis -> ehs : Not yet. HTTP 404 - no-content

...after some time...

ehs -> vis : Provide voter list changes (1)
vis -> ehs : Change list 1
ehs -> ehs : Import change list 1

...after some time...

ehs -> vis : Provide voter list changes (2)
vis -> ehs : Change list 2
ehs -> ehs : Import change list 2

deactivate vis
deactivate ehs
@enduml
