skinparam interface {
    backgroundColor<<TR_IVXV()>> Gold
    backgroundColor<<TR_EXTERNAL()>> LightSalmon
    backgroundColor<<TR_NEC()>> DarkGoldenRod
    backgroundColor<<TR_UNSPECIFIED()>> Black
}

skinparam actor {
    backgroundColor<<TR_IVXV()>> Gold
    backgroundColor<<TR_EXTERNAL()>> LightSalmon
    backgroundColor<<TR_NEC()>> DarkGoldenRod
    backgroundColor<<TR_UNSPECIFIED()>> Black
}

skinparam component {
    backgroundColor<<TR_IVXV()>> Gold
    backgroundColor<<TR_NEC()>> DarkGoldenRod
    backgroundColor<<TR_EXTERNAL()>> LightSalmon
    backgroundColor<<TR_UNSPECIFIED()>> Black
}
