@startuml

left to right direction

package VIS {

  component "VAL\n(läbi VTA)" as VAL {
  }

  component "KAN\n(läbi VTA)" as KAN {
  }

  component "3b - NIM otse,\nülejäänud - NIM läbi VTA" as NIM {
  }

  component "TUL\n(läbi VTA)" as TUL {
  }

  () "HTTPS API" as i_vta


  component "VTA" as VTA {

  }

  component "NIM" as NIM {
  }


}



package EHS {

  component "Haldusliides" as haldus

  () "X-road" as i_xroad

  component "Kogumisteenus" as collector

  component "Töötlemisrakendus" as processor

  component "Võtmerakendus" as key

}


VAL --> haldus: 1. Valimisringkondade nimekiri
KAN --> haldus: 2. Valikute nimekiri (kandidaatide nimekiri)

NIM --> haldus: 3a. Valijate nimekiri (algnimekiri)
NIM --> haldus: 3b. Valijate nimekiri (muudatused)
NIM --> processor: 4. E-hääletanute nimekiri
NIM --> processor: 5. Tühistus- ja ennistusnimekiri


TUL <-- key: 6. E-hääletamise tulemus

VTA - i_vta

i_vta <-- haldus: 7. E-hääletamisest osavõtu üldstatistika

i_vta <-- haldus: 8. E-hääletamisest osavõtu detailne statistika


NIM --> i_xroad: 9. e-hääletamise nimekiri
collector - i_xroad




@enduml
