@startuml

left to right direction

package VIS {

  component "VAL\n(via VTA)" as VAL {
  }

  component "KAN\n(via VTA)" as KAN {
  }

  component "3b - NIM direct,\nrest - NIM via VTA" as NIM {
  }

  component "TUL\n(via VTA)" as TUL {
  }

  () "HTTPS API" as i_vta


  component "VTA" as VTA {

  }

  component "NIM" as NIM {
  }


}



package EHS {

  component "Management interface" as haldus

  () "X-road" as i_xroad

  component "Collection service" as collector

  component "Processor" as processor

  component "Key application" as key

}


VAL --> haldus: 1. List of districts
KAN --> haldus: 2. List of choices / candidates

NIM --> haldus: 3a. List of voters (initial)
NIM --> haldus: 3b. List of voters (changeset)
NIM --> processor: 4. List of i-voters
NIM --> processor: 5. Revokation/restoration list


TUL <-- key: 6. Voting result

VTA - i_vta

i_vta <-- haldus: 7. Turnout

i_vta <-- haldus: 8. Detailed turnout


NIM --> i_xroad: 9. List of i-voters (during online phase)
collector - i_xroad




@enduml
